links:
  rails_name: "https://www.railstutorial.org/"
  rails_tutorial_org: "https://www.railstutorial.org/"
  rails_tutorial_jp: "https://railstutorial.jp/"
  ruby_on_rails: "https://rubyonrails.org/"
  rails_contact: "https://www.railstutorial.org/contact"
  rails_author: "https://www.michaelhartl.com/"
  rails_help: "https://github.com/mhartl/sample_app_6th_ed/blob/main/HELP.md"
  rails_book: "https://www.railstutorial.org/book"
  rails_news: "https://news.railstutorial.org/"

digits:
  length_name_max_50: 50
  length_email_max_255: 255
  length_password_min_6: 6

regex:
  email: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/'
